
apiVersion: v1
kind: Service
metadata:
  name: mysql-master-svc
  namespace: mysql-space
  labels: 
    name: mysql-master-svc
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: http
    nodePort: 32306
  selector:
    name: mysql-master-pod
