
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master-rc
  namespace: mysql-space
  labels:
    name: mysql-master-rc
spec:
  replicas: 1
  selector:
    name: mysql-master-pod
  template:
    metadata:
      labels: 
        name: mysql-master-pod #该pod拥有的标签，对应上面的spec.selector.name，否则匹配不上
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysql123"
        - name: MYSQL_REPLICATION_USER  
          value: "repl"
        - name: MYSQL_REPLICATION_PASSWORD  
          value: "repl123" 
        args:
        - --log-bin=mysql-bin
        - --binlog-ignore-db=mysql
        - --server-id=1001
        - --symbolic-links=0
        - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
