apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  labels:
    app: k8s-app
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - name: k8s-app
        image: k8s-app:1.0
        ports:
        - containerPort: 8089
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8089
          initialDelaySeconds: 30
          timeoutSeconds: 30
        imagePullPolicy: IfNotPresent
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app
  namespace: default
  labels:
    app: k8s-app
spec:
  ports:
  - port: 8089
    nodePort: 30089
  selector:
    app: k8s-app
  type: NodePort
